language: node_js
node_js:
  - '9.3.0'
script:
  - npm run build
after_success:
  - mv CNAME docs
  - mv 404.html docs
deploy:
  provider: pages
  skip-cleanup: true
  github-token: $GH_TOKEN
  keep-history: true
  local-dir: "./docs"
  on:
    branch: master